create_clock -period 10.000 -name clk [get_ports clk]

set_property PACKAGE_PIN L16 [get_ports {din[1]}]
set_property PACKAGE_PIN J15 [get_ports {din[0]}]
set_property PACKAGE_PIN K15 [get_ports {dout[1]}]
set_property PACKAGE_PIN H17 [get_ports {dout[0]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]